(() => {
  'use strict';
  const prefersReduced = window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  const page = document.body?.dataset?.page || 'home';
  function loadPremiumStyle(){const link=document.createElement('link');link.rel='stylesheet';link.href=(page==='home'?'':'../')+'css/premium.css';document.head.appendChild(link)}
  function addScrollProgress(){const bar=document.createElement('div');bar.className='nl-scroll-progress';bar.setAttribute('aria-hidden','true');document.body.appendChild(bar);const update=()=>{const doc=document.documentElement,max=doc.scrollHeight-doc.clientHeight;bar.style.transform=`scaleX(${max>0?doc.scrollTop/max:0})`};window.addEventListener('scroll',update,{passive:true});update()}
  function addAmbientParticles(){if(prefersReduced)return;const layer=document.createElement('div');layer.className='nl-particles';layer.setAttribute('aria-hidden','true');const symbols=['✦','·','✧','•','✦','◇'];for(let i=0;i<18;i++){const el=document.createElement('span');el.textContent=symbols[i%symbols.length];el.style.setProperty('--x',`${Math.random()*100}%`);el.style.setProperty('--y',`${Math.random()*100}%`);el.style.setProperty('--delay',`${Math.random()*-12}s`);el.style.setProperty('--duration',`${8+Math.random()*10}s`);el.style.setProperty('--size',`${8+Math.random()*10}px`);layer.appendChild(el)}document.body.appendChild(layer)}
  function addReveal(){const targets=document.querySelectorAll('.card,.course-card,.challenge-card,.mode-card,.stat-card,.panel,.lesson-card,.section,.how,.recommendation,.game-hero,.challenge-banner,.progress-hero,.profile-hero');if(!targets.length)return;if(prefersReduced||!('IntersectionObserver'in window)){targets.forEach(el=>el.classList.add('nl-visible'));return}const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('nl-visible');observer.unobserve(entry.target)}})},{threshold:.08,rootMargin:'0px 0px -35px 0px'});targets.forEach((el,index)=>{el.classList.add('nl-reveal');el.style.setProperty('--reveal-delay',`${Math.min(index*45,360)}ms`);observer.observe(el)})}
  function addTilt(){if(prefersReduced||!window.matchMedia('(pointer:fine)').matches)return;document.querySelectorAll('.course-card,.challenge-card,.mode-card').forEach(card=>{card.addEventListener('pointermove',event=>{const rect=card.getBoundingClientRect(),px=(event.clientX-rect.left)/rect.width,py=(event.clientY-rect.top)/rect.height;card.style.setProperty('--rx',`${(.5-py)*4}deg`);card.style.setProperty('--ry',`${(px-.5)*4}deg`);card.classList.add('nl-tilting')});card.addEventListener('pointerleave',()=>{card.classList.remove('nl-tilting');card.style.removeProperty('--rx');card.style.removeProperty('--ry')})})}
  function addRipple(){document.addEventListener('click',event=>{const button=event.target.closest('.btn,.filter,.nav-item');if(!button||prefersReduced)return;const rect=button.getBoundingClientRect(),ripple=document.createElement('span'),size=Math.max(rect.width,rect.height)*1.2;ripple.className='nl-ripple';ripple.style.width=`${size}px`;ripple.style.height=`${size}px`;ripple.style.left=`${event.clientX-rect.left-size/2}px`;ripple.style.top=`${event.clientY-rect.top-size/2}px`;button.appendChild(ripple);window.setTimeout(()=>ripple.remove(),600)})}
  function addMobileNav(){if(window.innerWidth>900||document.querySelector('.nl-mobile-nav'))return;const base=page==='home'?'':'../';const items=[['home','⌂','Inicio','index.html'],['aprender','◈','Aprender','pages/aprender.html'],['juegos','◆','Juegos','pages/juegos.html'],['retos','⚡','Retos','pages/retos.html'],['perfil','●','Perfil','pages/perfil.html']];const nav=document.createElement('nav');nav.className='nl-mobile-nav';nav.setAttribute('aria-label','Navegación principal móvil');nav.innerHTML=items.map(([id,icon,label,path])=>`<a class="${page===id?'active':''}" href="${base}${path}"><span aria-hidden="true">${icon}</span><small>${label}</small></a>`).join('');document.body.appendChild(nav)}
  function removeFloatingMessages(){const clean=()=>document.querySelectorAll('.nx-toast,.toast-stack,.toast').forEach(el=>el.remove());clean();if('MutationObserver'in window){const observer=new MutationObserver(clean);observer.observe(document.body,{childList:true,subtree:true});}}
  function addLandscapeMode(){const sync=()=>document.body.classList.toggle('nl-landscape',window.matchMedia('(orientation: landscape) and (max-height: 600px)').matches);sync();window.addEventListener('resize',sync,{passive:true})}
  function addStickers(){/* Desactivado: no se generan mensajes decorativos flotantes. */}
  function addBackTop(){const button=document.createElement('button');button.className='nl-back-top';button.type='button';button.setAttribute('aria-label','Volver arriba');button.textContent='↑';document.body.appendChild(button);const update=()=>button.classList.toggle('show',window.scrollY>420);window.addEventListener('scroll',update,{passive:true});button.addEventListener('click',()=>window.scrollTo({top:0,behavior:prefersReduced?'auto':'smooth'}));update()}
  function addKeyboardFocus(){document.addEventListener('keydown',event=>{if(event.key==='Escape')document.querySelectorAll('.modal-backdrop,.nl-game-modal').forEach(modal=>modal.remove())})}
  function confetti(){if(prefersReduced)return;const colors=['#6957ff','#ff6f91','#45cbea','#59d9b4','#ffd45c','#fff'],wrap=document.createElement('div');wrap.className='nl-confetti';wrap.setAttribute('aria-hidden','true');for(let i=0;i<34;i++){const piece=document.createElement('i');piece.style.setProperty('--c',colors[i%colors.length]);piece.style.setProperty('--x',`${Math.random()*100}%`);piece.style.setProperty('--dx',`${(Math.random()-.5)*260}px`);piece.style.setProperty('--delay',`${Math.random()*180}ms`);piece.style.setProperty('--rot',`${Math.random()*720-360}deg`);wrap.appendChild(piece)}document.body.appendChild(wrap);window.setTimeout(()=>wrap.remove(),2200)}
  function addLevelCelebrationObserver(){if(prefersReduced||!('MutationObserver'in window))return;const observer=new MutationObserver(mutations=>{for(const mutation of mutations)for(const node of mutation.addedNodes){if(!(node instanceof HTMLElement))continue;const modal=node.matches('.modal-backdrop')?node:node.querySelector?.('.modal-backdrop');if(modal&&/SUBISTE DE NIVEL|nivel/i.test(modal.textContent||''))confetti()}});observer.observe(document.body,{childList:true,subtree:true})}
  function init(){loadPremiumStyle();addScrollProgress();addAmbientParticles();addReveal();addTilt();addRipple();addMobileNav();removeFloatingMessages();addLandscapeMode();addStickers();addBackTop();addKeyboardFocus();addLevelCelebrationObserver();document.body.classList.add('nl-enhanced')}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
