(() => {
  'use strict';
  if (document.body?.dataset?.page !== 'juegos') return;

  const style = document.createElement('style');
  style.textContent = `
    .nl-games-shell{margin-top:24px;min-width:0}
    .nl-games-intro{display:grid;grid-template-columns:minmax(0,1.3fr) minmax(220px,.7fr);gap:18px;margin-bottom:20px}
    .nl-game-welcome{padding:26px;border-radius:28px;background:linear-gradient(135deg,#7568ff,#ff7197 62%,#ffd45c);color:#fff;position:relative;overflow:hidden;box-shadow:0 18px 45px rgba(93,76,190,.2)}
    .nl-game-welcome h2{font-size:clamp(1.8rem,4vw,2.8rem);margin:5px 0 8px;font-weight:900}
    .nl-game-welcome p{max-width:680px;margin:0;color:rgba(255,255,255,.92);line-height:1.6}
    .nl-game-stats{display:grid;grid-template-columns:1fr 1fr;gap:10px}
    .nl-game-stat{padding:18px;border-radius:22px;background:#fff;border:1px solid #ebe8f5;box-shadow:0 12px 30px rgba(35,28,80,.06);min-width:0}
    .nl-game-stat b{display:block;font-size:1.5rem;overflow-wrap:anywhere}.nl-game-stat span{font-size:.78rem;color:#77758a}
    .nl-game-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}
    .nl-game-card{min-height:300px;border:1px solid #e8e4f2;border-radius:26px;padding:22px;background:#fff;box-shadow:0 12px 35px rgba(35,28,80,.07);display:flex;flex-direction:column;position:relative;overflow:hidden;transition:transform .22s,box-shadow .22s}
    .nl-game-card:hover{transform:translateY(-5px);box-shadow:0 24px 50px rgba(54,42,120,.14)}
    .nl-game-art{width:76px;height:76px;border-radius:24px;display:grid;place-items:center;font-size:2.4rem;margin-bottom:14px;background:linear-gradient(135deg,#eeeaff,#fff0f5);flex:none}
    .nl-game-card:nth-child(2) .nl-game-art{background:linear-gradient(135deg,#fff0bf,#eaf5ff)}.nl-game-card:nth-child(3) .nl-game-art{background:linear-gradient(135deg,#dffaf0,#eaf5ff)}.nl-game-card:nth-child(4) .nl-game-art{background:linear-gradient(135deg,#e8e2ff,#fff0d8)}.nl-game-card:nth-child(5) .nl-game-art{background:linear-gradient(135deg,#ffe2ea,#eee7ff)}.nl-game-card:nth-child(6) .nl-game-art{background:linear-gradient(135deg,#dff7ff,#fff0c7)}
    .nl-game-card h3{margin:4px 0 8px;font-size:1.35rem}.nl-game-card p{color:#69677a;line-height:1.55;margin:0}.nl-game-tag{font-size:.7rem;font-weight:900;letter-spacing:.08em;color:#7568ff}
    .nl-game-card .nl-play{margin-top:auto;padding-top:18px}.nl-play button{width:100%;min-height:50px;border:0;border-radius:15px;background:#28233e;color:#fff;font:inherit;font-weight:900;cursor:pointer;transition:.2s}.nl-play button:hover{background:#7568ff;transform:translateY(-2px)}
    .nl-game-modal{position:fixed;inset:0;z-index:30000;background:rgba(22,18,42,.72);backdrop-filter:blur(8px);display:grid;place-items:center;padding:clamp(8px,2vw,20px)}
    .nl-game-panel{width:min(960px,100%);max-height:94dvh;overflow:auto;background:#fff;border-radius:30px;padding:24px;box-shadow:0 35px 100px rgba(0,0,0,.3);overscroll-behavior:contain}
    .nl-game-top{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.nl-game-top h2{margin:4px 0 0;overflow-wrap:anywhere}.nl-game-close{border:0;background:#f0eef7;border-radius:12px;padding:10px 13px;cursor:pointer;font-weight:900;flex:none}
    .nl-game-progress{height:10px;background:#eeeef5;border-radius:99px;overflow:hidden;margin:12px 0 22px}.nl-game-progress i{display:block;height:100%;background:linear-gradient(90deg,#7568ff,#ff7197,#ffd45c);transition:.3s}
    .nl-q{font-size:1.3rem;font-weight:900;line-height:1.4}.nl-options{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:11px;margin-top:18px}.nl-option{min-height:54px;padding:13px 15px;border-radius:15px;border:2px solid #e3e0ed;background:#fff;text-align:left;font:inherit;font-weight:800;cursor:pointer}.nl-option:hover{border-color:#7568ff;background:#f8f7ff}.nl-option.ok{background:#e3faef;border-color:#36bd83}.nl-option.no{background:#ffebef;border-color:#f06b88}
    .nl-feedback{margin-top:16px;padding:14px 16px;border-radius:16px;background:#f7f5ff;color:#3c3850;line-height:1.55}.nl-next{margin-top:15px;min-height:48px;padding:12px 18px;border:0;border-radius:15px;background:#7568ff;color:#fff;font:inherit;font-weight:900;cursor:pointer}.nl-next:disabled{opacity:.55;cursor:not-allowed}
    .nl-result{text-align:center;padding:18px}.nl-result-score{font-size:clamp(2.5rem,8vw,3.2rem);font-weight:900;color:#7568ff}.nl-result-actions{display:flex;justify-content:center;gap:10px;flex-wrap:wrap}.nl-result-actions button{min-height:48px;border:0;border-radius:14px;padding:12px 18px;font:inherit;font-weight:900;cursor:pointer}.nl-primary{background:#7568ff;color:#fff}.nl-secondary{background:#eeeafb;color:#3e3858}
    .nl-experiment{display:grid;grid-template-columns:1fr 1fr;gap:18px}.nl-control{padding:15px;background:#f8f7fc;border-radius:16px;margin:10px 0}.nl-control label{display:flex;justify-content:space-between;gap:12px;font-weight:800}.nl-control input{width:100%}.nl-plant{text-align:center;font-size:7rem;transition:.4s}
    .nl-timeline{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0}.nl-timeline button{border:2px solid #e0ddec;background:#f8f7fc;border-radius:14px;padding:12px;font-weight:900;cursor:pointer}.nl-timeline button.active{background:#7568ff;color:#fff;border-color:#7568ff}
    .nl-game-note{font-size:.9rem;color:#706d80;margin:8px 0 0}.nl-ludo{display:grid;grid-template-columns:minmax(280px,1fr) minmax(220px,.7fr);gap:18px;align-items:start}.nl-ludo-board{aspect-ratio:1;max-width:560px;margin:auto;display:grid;grid-template-columns:repeat(15,1fr);grid-template-rows:repeat(15,1fr);background:#f5f3fb;border:5px solid #29233f;border-radius:22px;padding:5px;box-shadow:inset 0 0 0 2px #fff;overflow:hidden}.ludo-cell{position:relative;border:1px solid rgba(45,39,67,.1);display:grid;place-items:center;min-width:0}.ludo-path{background:#fff}.ludo-home.red{background:#ffdce5}.ludo-home.blue{background:#dff2ff}.ludo-home.green{background:#dcf8ea}.ludo-home.yellow{background:#fff1c7}.ludo-center{background:linear-gradient(135deg,#7568ff,#ff7197)}.ludo-token{width:72%;aspect-ratio:1;border-radius:50%;border:3px solid #fff;box-shadow:0 2px 6px rgba(0,0,0,.22);cursor:pointer;z-index:2}.ludo-token.red{background:#ef5d78}.ludo-token.blue{background:#4aa9e8}.ludo-token.green{background:#42bd86}.ludo-token.yellow{background:#f4bf3e}.ludo-token.movable{animation:nlPulse 1s infinite;outline:3px solid rgba(117,104,255,.45)}.nl-ludo-controls{display:grid;gap:12px}.nl-die{width:90px;height:90px;border:0;border-radius:22px;background:#fff;box-shadow:0 12px 30px rgba(35,28,80,.12);font-size:3.4rem;cursor:pointer}.nl-die:disabled{opacity:.5;cursor:not-allowed}.nl-player-list{display:grid;gap:8px}.nl-player{padding:12px;border:2px solid #ebe8f5;border-radius:14px;background:#fff;font-weight:800}.nl-player.active{border-color:#7568ff;background:#f5f2ff}.nl-status{padding:13px;border-radius:15px;background:#f7f5ff;line-height:1.5}.nl-progress-mini{height:8px;background:#eceaf3;border-radius:99px;overflow:hidden}.nl-progress-mini i{display:block;height:100%;background:#7568ff}
    .nl-jenga{display:grid;grid-template-columns:minmax(240px,.9fr) minmax(280px,1.1fr);gap:20px;align-items:end}.jenga-stage{min-height:420px;background:linear-gradient(180deg,#f6f4ff,#fff);border-radius:22px;padding:24px;display:flex;align-items:flex-end;justify-content:center;overflow:hidden}.jenga-tower{width:min(300px,80%);display:flex;flex-direction:column-reverse;gap:5px}.jenga-row{height:38px;display:flex;gap:5px;justify-content:center}.jenga-row:nth-child(even){transform:rotate(90deg);margin:0 -15px}.jenga-block{flex:1;max-width:92px;border:2px solid #b87842;border-radius:7px;background:linear-gradient(180deg,#f7c681,#d99855);box-shadow:0 3px 4px rgba(80,45,20,.18);cursor:pointer;transition:.18s;min-width:0}.jenga-block:hover{transform:translateY(-4px)}.jenga-block.used{opacity:.18;cursor:not-allowed;transform:none}.jenga-block.target{outline:3px solid #7568ff;animation:nlPulse 1s infinite}.jenga-side{display:grid;gap:12px}.jenga-question{font-size:1.15rem;font-weight:900;line-height:1.45}.jenga-options{display:grid;gap:9px}.jenga-answer{padding:12px;border:2px solid #e4e1ed;border-radius:13px;background:#fff;text-align:left;font:inherit;font-weight:800;cursor:pointer}.jenga-answer:hover{border-color:#7568ff}.jenga-answer.ok{border-color:#36bd83;background:#e3faef}.jenga-answer.no{border-color:#f06b88;background:#ffebef}
    @keyframes nlPulse{50%{transform:translateY(-3px) scale(1.03)}}
    @media(max-width:820px){.nl-games-intro,.nl-game-grid,.nl-experiment,.nl-ludo,.nl-jenga{grid-template-columns:1fr}.nl-game-card{min-height:260px}.nl-options{grid-template-columns:1fr}.nl-ludo-board{max-width:620px}.jenga-stage{min-height:340px}}
    @media(max-width:600px){.nl-game-panel{padding:16px;border-radius:22px}.nl-game-top h2{font-size:1.35rem}.nl-game-welcome{padding:21px}.nl-game-grid{gap:12px}.nl-game-card{padding:18px;border-radius:21px}.nl-game-art{width:64px;height:64px;font-size:2rem}.nl-game-stats{grid-template-columns:1fr 1fr}.nl-game-stat{padding:14px}.nl-game-stat b{font-size:1.15rem}.nl-die{width:76px;height:76px}.jenga-stage{min-height:300px;padding:16px}.jenga-row{height:31px}}
    @media(orientation:landscape) and (max-height:600px){.nl-game-modal{padding:7px}.nl-game-panel{max-height:97dvh;padding:14px;border-radius:18px}.nl-game-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.nl-game-card{min-height:220px;padding:16px}.nl-ludo{grid-template-columns:minmax(300px,1fr) minmax(220px,.7fr)}.nl-ludo-board{max-height:78dvh}.nl-jenga{grid-template-columns:1fr 1fr}.jenga-stage{min-height:330px}}
  `;
  document.head.appendChild(style);

  const games = [
    ['ludo','🎲','ESTRATEGIA · MATEMÁTICA','Ludo de Desafíos','Juega por turnos, resuelve desafíos y lleva tus fichas hasta la meta.',80],
    ['jenga','🧱','COMUNICACIÓN · ARGUMENTACIÓN','Jenga de Ideas','Retira bloques, responde y construye argumentos sin derribar la torre.',70],
    ['math','➗','MATEMÁTICA · CÁLCULO','Arena Matemática','Números, porcentajes, fracciones y geometría.',60],
    ['sci','🧪','CIENCIA · EXPERIMENTACIÓN','Laboratorio de Hipótesis','Manipula variables, predice resultados y compara evidencias.',60],
    ['soc','🗺️','SOCIALES · PENSAMIENTO HISTÓRICO','Expedición Andina','Conecta territorio, organización, caminos y legado del mundo andino.',70]
  ];

  const state = () => { try { return window.NLStorage?.load?.() || null; } catch { return null; } };
  const rewardOnce = (xp, course, key) => {
    const s = state(); if (!s) return false;
    s.metaJuegos = Array.isArray(s.metaJuegos) ? s.metaJuegos : [];
    const marker = `${key}:${new Date().toISOString().slice(0,10)}`;
    if (s.metaJuegos.includes(marker)) return false;
    s.metaJuegos.push(marker); s.metaJuegos = s.metaJuegos.slice(-100);
    s.xp = (Number(s.xp)||0) + xp; s.puntos = (Number(s.puntos)||0) + Math.round(xp*.6);
    s.stats = s.stats || {actividades:0,porCurso:{}}; s.stats.actividades=(Number(s.stats.actividades)||0)+1;
    s.stats.porCurso=s.stats.porCurso||{}; s.stats.porCurso[course]=(Number(s.stats.porCurso[course])||0)+1;
    try { window.NLStorage.save(s); } catch {}
    return true;
  };
  const close = m => m?.remove();
  const esc = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

  function modal(title){
    const m=document.createElement('div'); m.className='nl-game-modal';
    m.innerHTML=`<section class="nl-game-panel" role="dialog" aria-modal="true" aria-label="${esc(title)}"><div class="nl-game-top"><div><span class="eyebrow">NEXT LEVEL · JUEGO DIDÁCTICO</span><h2>${esc(title)}</h2></div><button class="nl-game-close" aria-label="Cerrar">✕</button></div><div class="nl-game-body"></div></section>`;
    document.body.appendChild(m); m.querySelector('.nl-game-close').onclick=()=>close(m); m.addEventListener('click',e=>{if(e.target===m)close(m)}); return m;
  }

  function quiz(title,course,qs,xp,key){
    let i=0,score=0,locked=false; const m=modal(title),body=m.querySelector('.nl-game-body');
    body.innerHTML='<div class="nl-game-progress"><i></i></div><div class="q"></div>'; const bar=body.querySelector('i'),q=body.querySelector('.q');
    const render=()=>{locked=false;if(i>=qs.length){rewardOnce(xp,course,key);q.innerHTML=`<div class="nl-result"><div class="nl-result-score">${score}/${qs.length}</div><h3>${score===qs.length?'🌟 ¡Perfecto!':score>=3?'👏 ¡Buen trabajo!':'💪 Sigue practicando'}</h3><p>Correctas: <b>${score}</b> de ${qs.length}. Recompensa máxima: <b>+${xp} XP</b>.</p><div class="nl-result-actions"><button class="nl-primary" id="again">Jugar otra vez</button><button class="nl-secondary" id="finish">Cerrar</button></div></div>`;q.querySelector('#again').onclick=()=>{close(m);quiz(title,course,qs,xp,key+':replay')};q.querySelector('#finish').onclick=()=>close(m);return}bar.style.width=`${i/qs.length*100}%`;const x=qs[i];q.innerHTML=`<span class="eyebrow">PREGUNTA ${i+1} DE ${qs.length}</span><div class="nl-q">${esc(x.q)}</div><div class="nl-options">${x.a.map((a,n)=>`<button class="nl-option" data-i="${n}">${esc(a)}</button>`).join('')}</div><div id="fb"></div>`;q.querySelectorAll('.nl-option').forEach(b=>b.onclick=()=>{if(locked)return;locked=true;const ok=+b.dataset.i===x.c;b.classList.add(ok?'ok':'no');if(ok)score++;else q.querySelectorAll('.nl-option')[x.c]?.classList.add('ok');q.querySelector('#fb').innerHTML=`<div class="nl-feedback"><b>${ok?'✓ Correcto':'✕ Revisa la respuesta'}</b><br>${esc(x.e)}</div><button class="nl-next">${i===qs.length-1?'Ver resultado':'Siguiente →'}</button>`;q.querySelector('.nl-next').onclick=()=>{i++;render()}})}; render();
  }

  const math=()=>quiz('➗ Arena Matemática','matematica',[{q:'12 × 4 = ?',a:['36','48','52','44'],c:1,e:'12 grupos de 4 forman 48.'},{q:'¿Cuál es 3/4 de 20?',a:['12','14','15','16'],c:2,e:'20 ÷ 4 = 5 y 5 × 3 = 15.'},{q:'S/50 con 20% de descuento. ¿Precio final?',a:['S/30','S/35','S/40','S/45'],c:2,e:'El 20% de 50 es 10; 50 − 10 = 40.'},{q:'Área de un rectángulo de 7 m por 5 m.',a:['24 m²','30 m²','35 m²','40 m²'],c:2,e:'Área = base × altura = 7 × 5 = 35 m².'},{q:'−3 + 8 = ?',a:['−11','−5','5','11'],c:2,e:'Desde −3 avanzas 8 unidades: llegas a 5.'}],60,'math');

  function sci(){const m=modal('🧪 Laboratorio de Hipótesis'),b=m.querySelector('.nl-game-body');b.innerHTML=`<div class="nl-experiment"><div><div class="nl-control"><label><span>Horas de luz</span><b id="lv">8 h</b></label><input id="light" type="range" min="0" max="16" value="8"></div><div class="nl-control"><label><span>Agua</span><b id="wv">50%</b></label><input id="water" type="range" min="0" max="100" value="50"></div><button class="nl-next" id="run">▶ Ejecutar experimento</button><p class="nl-game-note">Hipótesis: más luz y agua adecuada deberían favorecer el crecimiento.</p></div><div><div class="nl-plant" id="plant">🌱</div><div class="nl-feedback" id="result">Ajusta las variables y ejecuta el experimento.</div></div></div>`;const l=b.querySelector('#light'),w=b.querySelector('#water');l.oninput=()=>b.querySelector('#lv').textContent=l.value+' h';w.oninput=()=>b.querySelector('#wv').textContent=w.value+'%';b.querySelector('#run').onclick=()=>{const light=+l.value,water=+w.value;const waterFit=Math.max(0,100-Math.abs(water-65)*1.5);const g=Math.round(light/16*55+waterFit*.45);b.querySelector('#plant').style.transform=`scale(${.7+g/100})`;b.querySelector('#result').innerHTML=`<b>Resultado: ${g}% de crecimiento simulado.</b><br>${g>=70?'Condiciones favorables.':g>=45?'Crecimiento moderado.':'Condiciones poco favorables.'}<br><br>💡 Para investigar bien, cambia una sola variable cada vez.`;rewardOnce(60,'ciencia','sci')}}

  function soc(){const m=modal('🗺️ Expedición Andina'),b=m.querySelector('.nl-game-body'),ev=[['Origen y expansión','El Tahuantinsuyo se expandió desde Cusco hacia distintas regiones.'],['Organización','La administración del territorio se apoyó en formas de organización y trabajo.'],['Red vial','Los caminos facilitaron comunicación e intercambio.'],['Legado','El mundo andino dejó conocimientos, obras, lenguas y tradiciones.']];let step=0;b.innerHTML=`<p>Desbloquea la ruta en orden y conecta cada etapa.</p><div class="nl-timeline">${ev.map((x,n)=>`<button data-n="${n}" class="${n===0?'active':''}">${n+1}. ${x[0]}</button>`).join('')}</div><div class="nl-feedback" id="route">${ev[0][1]}</div><button class="nl-next" id="next">Desbloquear siguiente →</button>`;const nodes=b.querySelectorAll('[data-n]');nodes.forEach(n=>n.onclick=()=>{const x=+n.dataset.n;if(x<=step)b.querySelector('#route').textContent=ev[x][1]});b.querySelector('#next').onclick=()=>{if(step<3){step++;nodes[step].classList.add('active');b.querySelector('#route').innerHTML=`<b>🔓 ${ev[step][0]}</b><br>${ev[step][1]}`}else{b.querySelector('#route').innerHTML='<b>🏆 Expedición completada.</b><br>Conectaste las cuatro etapas.';b.querySelector('#next').disabled=true;rewardOnce(70,'sociales','soc')}}}

  const LUDO={size:15,path:[[6,1],[6,2],[6,3],[6,4],[6,5],[5,6],[4,6],[3,6],[2,6],[1,6],[0,6],[0,7],[0,8],[1,8],[2,8],[3,8],[4,8],[5,8],[6,9],[6,10],[6,11],[6,12],[6,13],[6,14],[7,14],[8,14],[8,13],[8,12],[8,11],[8,10],[8,9],[9,8],[10,8],[11,8],[12,8],[13,8],[14,8],[14,7],[14,6],[13,6],[12,6],[11,6],[10,6],[9,6],[8,5],[8,4],[8,3],[8,2],[8,1],[8,0],[7,0],[6,0]],starts:{red:0,blue:13,green:26,yellow:39},colors:['red','blue','green','yellow'],questions:[{q:'Si lanzas 4 y avanzas 3 casillas, ¿cuántas recorres en total?',a:['1','3','4','7'],c:3,e:'Avanzas 3; el número del dado solo determina cuánto puedes mover.'},{q:'¿Qué fracción equivale a 0,5?',a:['1/4','1/2','2/3','3/4'],c:1,e:'0,5 es equivalente a un medio.'},{q:'Si una ficha está en la casilla 8 y avanza 5, ¿en qué casilla queda?',a:['3','12','13','40'],c:1,e:'8 + 5 = 13.'},{q:'S/80 con 25% de descuento queda en…',a:['S/20','S/55','S/60','S/75'],c:2,e:'25% de 80 es 20; 80 − 20 = 60.'}]};
  function ludo(){const m=modal('🎲 Ludo de Desafíos'),b=m.querySelector('.nl-game-body');let turn=0,roll=0,waiting=true,positions={red:[-1,-1,-1,-1],blue:[-1,-1,-1,-1],green:[-1,-1,-1,-1],yellow:[-1,-1,-1,-1]},finished=false;const players=LUDO.colors;function absIndex(color,p){return (LUDO.starts[color]+p)%52}function winner(c){return positions[c].every(p=>p>=51)}function cell(x,y){return `<div class="ludo-cell ${x<6&&y<6?'ludo-home red':x<6&&y>8?'ludo-home blue':x>8&&y>8?'ludo-home green':x>8&&y<6?'ludo-home yellow':x>=6&&x<=8&&y>=6&&y<=8?'ludo-center':'ludo-path'} data-x="${x}" data-y="${y}"></div>`}function draw(){b.querySelector('.nl-ludo-board').innerHTML=Array.from({length:15},(_,y)=>Array.from({length:15},(_,x)=>cell(x,y)).join('')).join('');LUDO.path.forEach(([x,y],idx)=>{const el=b.querySelector(`[data-x="${x}"][data-y="${y}"]`);if(el){el.dataset.path=idx;el.classList.add('ludo-path')}});players.forEach(c=>positions[c].forEach((p,i)=>{if(p<0)return;const [x,y]=LUDO.path[absIndex(c,p)];const el=b.querySelector(`[data-x="${x}"][data-y="${y}"]`);if(!el)return;const token=document.createElement('button');token.className=`ludo-token ${c} ${waiting&&c===players[turn]&&canMove(c,i,roll)?'movable':''}`;token.title=`Ficha ${i+1}`;token.setAttribute('aria-label',`Ficha ${i+1} ${c}`);token.onclick=()=>move(c,i);el.appendChild(token)});const current=players[turn];b.querySelector('#ludo-turn').textContent=`Turno: ${current.toUpperCase()} · ${turn+1}/4`;b.querySelector('#ludo-die').textContent=roll?['','⚀','⚁','⚂','⚃','⚄','⚅'][roll]:'🎲';b.querySelector('#ludo-die').disabled=!waiting||finished;b.querySelector('#ludo-status').textContent=finished?'🏆 Partida terminada.':waiting?(roll?`Sacaste ${roll}. Pulsa una ficha que pueda avanzar.`:'Lanza el dado para comenzar.'):'Responde el desafío para mover.';players.forEach((c,i)=>{const el=b.querySelector(`#p-${c}`);el.classList.toggle('active',i===turn);el.querySelector('i').style.width=`${positions[c].filter(p=>p>=51).length/4*100}%`})}
    function canMove(c,i,r){return r>0&&positions[c][i]>=0?positions[c][i]+r<=51:true}
    function nextTurn(){roll=0;waiting=true;turn=(turn+1)%4;draw()}
    function move(c,i){if(finished||c!==players[turn]||!waiting||!canMove(c,i,roll))return;waiting=false;const q=LUDO.questions[(turn+i+roll)%LUDO.questions.length];const box=b.querySelector('#ludo-challenge');box.innerHTML=`<div class="nl-q">${q.q}</div><div class="nl-options">${q.a.map((a,n)=>`<button class="nl-option" data-i="${n}">${a}</button>`).join('')}</div><div class="nl-game-note">${q.e}</div>`;box.querySelectorAll('.nl-option').forEach(btn=>btn.onclick=()=>{box.querySelectorAll('.nl-option').forEach(x=>x.disabled=true);const ok=+btn.dataset.i===q.c;btn.classList.add(ok?'ok':'no');if(ok){positions[c][i]=positions[c][i]<0?roll-1:positions[c][i]+roll; if(positions[c][i]>51)positions[c][i]=51;if(winner(c)){finished=true;rewardOnce(80,'matematica','ludo');box.innerHTML='<div class="nl-result"><div class="nl-result-score">🏆</div><h3>¡Ganaste el Ludo!</h3><p>Completaste tus 4 fichas resolviendo desafíos.</p><button class="nl-primary" id="close">Cerrar</button></div>';b.querySelector('#close').onclick=()=>close(m);draw();return}box.innerHTML='<div class="nl-feedback"><b>✓ Desafío superado.</b> Tu ficha avanza.</div>';setTimeout(nextTurn,500)}else{box.innerHTML=`<div class="nl-feedback"><b>✕ No avanzas esta vez.</b><br>${q.e}</div>`;setTimeout(nextTurn,900)}})}
    b.innerHTML=`<div class="nl-ludo"><div><div class="nl-ludo-board"></div><p class="nl-game-note">Regla educativa: necesitas resolver el desafío para mover la ficha. Cada color representa un jugador local.</p></div><div class="nl-ludo-controls"><div class="nl-status" id="ludo-turn"></div><button class="nl-die" id="ludo-die" aria-label="Lanzar dado">🎲</button><div class="nl-player-list">${players.map(c=>`<div class="nl-player" id="p-${c}">${c.toUpperCase()} <span>· 4 fichas</span><div class="nl-progress-mini"><i></i></div></div>`).join('')}</div><div class="nl-status" id="ludo-status"></div><div id="ludo-challenge" class="nl-feedback">Lanza el dado. ¡La primera ficha comienza fuera del tablero!</div></div></div>`;
    b.querySelector('#ludo-die').onclick=()=>{if(!waiting||finished)return;roll=Math.floor(Math.random()*6)+1;draw()};draw();
  }

  function jenga(){const m=modal('🧱 Jenga de Ideas'),b=m.querySelector('.nl-game-body');let removed=0,round=0,locked=false;const qs=[{q:'¿Qué conector indica contraste?',a:['porque','sin embargo','además','por eso'],c:1,e:'“Sin embargo” introduce una oposición.'},{q:'¿Qué fortalece más un argumento?',a:['Hablar más fuerte','Una razón con evidencia','Repetición','Palabras difíciles'],c:1,e:'La evidencia permite respaldar la razón.'},{q:'Una inferencia debe…',a:['Inventar datos','Basarse en pistas','Ignorar contexto','Repetir palabras'],c:1,e:'Inferir es concluir a partir de pistas y conocimientos.'},{q:'¿Qué es una conclusión?',a:['Una pregunta','Un título','Una idea final derivada de razones','Una palabra clave'],c:2,e:'La conclusión sintetiza lo que se puede sostener.'},{q:'¿Cuál es una idea principal?',a:['Un detalle aislado','La idea central del texto','Una palabra difícil','Una opinión sin relación'],c:1,e:'Resume lo esencial de un texto o fragmento.'}];
    const blocks=Array.from({length:18},(_,i)=>({id:i,used:false}));function draw(){const tower=b.querySelector('.jenga-tower');tower.innerHTML='';for(let r=0;r<6;r++){const row=document.createElement('div');row.className='jenga-row';for(let j=0;j<3;j++){const block=blocks[r*3+j];const btn=document.createElement('button');btn.className=`jenga-block ${block.used?'used':''}`;btn.dataset.id=block.id;btn.disabled=block.used;btn.setAttribute('aria-label',`Bloque ${block.id+1}`);btn.onclick=()=>select(block);row.appendChild(btn)}tower.appendChild(row)}}function select(block){if(locked||block.used||removed>=12)return;locked=true;const q=qs[round%qs.length],side=b.querySelector('.jenga-side');side.querySelector('.jenga-question').textContent=q.q;side.querySelector('.jenga-options').innerHTML=q.a.map((a,n)=>`<button class="jenga-answer" data-i="${n}">${a}</button>`).join('');side.querySelector('.nl-game-note').textContent='Responde correctamente para retirar el bloque sin perder la ronda.';side.querySelectorAll('.jenga-answer').forEach(x=>x.onclick=()=>{const ok=+x.dataset.i===q.c;side.querySelectorAll('.jenga-answer').forEach(y=>y.disabled=true);x.classList.add(ok?'ok':'no');if(ok){block.used=true;removed++;round++;draw();side.querySelector('.nl-game-note').textContent=`✓ Bloque retirado. ${12-removed} bloques seguros restantes.`;if(removed>=12){rewardOnce(70,'comunicacion','jenga');side.querySelector('.jenga-question').textContent='🏆 ¡Torre completada!';side.querySelector('.jenga-options').innerHTML='<button class="nl-primary" id="jclose">Cerrar</button>';side.querySelector('#jclose').onclick=()=>close(m)}}else{side.querySelector('.nl-game-note').textContent=`✕ Respuesta incorrecta. ${q.e}`;round++;}locked=false})})}
    b.innerHTML=`<div class="nl-jenga"><div class="jenga-stage"><div class="jenga-tower"></div></div><div class="jenga-side"><div class="nl-status"><b>Objetivo:</b> retirar 12 de 18 bloques respondiendo desafíos.</div><div class="jenga-question">Elige un bloque para comenzar.</div><div class="jenga-options"><p class="nl-game-note">Cada bloque retirado exige una respuesta. La torre se mantiene estable de forma simulada para priorizar el aprendizaje.</p></div><p class="nl-game-note">Progreso: <b id="jprogress">0/12</b></p></div></div>`;draw();new MutationObserver(()=>{const p=b.querySelector('#jprogress');if(p)p.textContent=`${removed}/12`}).observe(b,{subtree:true,childList:true});
  }

  function mount(){const root=document.querySelector('#app'),main=root?.querySelector('main.main');if(!main)return;root.querySelector('.area-modes')?.remove();const s=state()||{};const section=document.createElement('section');section.className='nl-games-shell';section.innerHTML=`<div class="nl-games-intro"><div class="nl-game-welcome"><span class="pill">JUEGA PARA COMPRENDER</span><h2>Aprende haciendo.</h2><p>Ahora los juegos tienen reglas, estados, feedback y recompensas reales. Elige una misión y comprueba cuánto puedes avanzar.</p></div><div class="nl-game-stats"><div class="nl-game-stat"><span>Tu nivel</span><b>⭐ ${s.nivel||1}</b></div><div class="nl-game-stat"><span>XP acumulado</span><b>⚡ ${s.xp||0}</b></div></div></div><div class="nl-game-grid">${games.map(g=>`<article class="nl-game-card"><div class="nl-game-art">${g[1]}</div><span class="nl-game-tag">${g[2]}</span><h3>${g[3]}</h3><p>${g[4]}</p><div class="nl-play"><button data-game="${g[0]}">Jugar ahora · +${g[5]} XP</button></div></article>`).join('')}</div>`;main.appendChild(section);const handlers={math,jenga,ludo,sci,soc};section.querySelectorAll('[data-game]').forEach(btn=>btn.onclick=()=>handlers[btn.dataset.game]?.())}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else setTimeout(mount,30);
})();
