(() => {
  'use strict';

  const page = document.body?.dataset?.page || 'home';
  const state = () => NLStorage.load();
  const $ = (s, root=document) => root.querySelector(s);
  const $$ = (s, root=document) => [...root.querySelectorAll(s)];
  const esc = x => String(x ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const base = page === 'home' ? '' : '..';
  const save = s => NLStorage.save(s);

  const css = `
  .nx-zone{margin-top:26px}.nx-toolbar{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin:0 0 18px}
  .nx-card{background:var(--surface,#fff);border:1px solid var(--border,#e6e8ef);border-radius:22px;padding:20px;box-shadow:0 10px 30px rgba(25,32,56,.06)}
  .nx-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:16px}
  .nx-kicker{font-size:.72rem;letter-spacing:.12em;font-weight:800;opacity:.62;text-transform:uppercase}.nx-title{margin:.3rem 0 .45rem;font-size:1.4rem}.nx-muted{color:var(--muted,#6b7280)}
  .nx-btn{border:0;border-radius:14px;padding:12px 16px;font-weight:800;cursor:pointer;background:#111827;color:#fff;transition:.2s transform,.2s box-shadow}.nx-btn:hover{transform:translateY(-2px);box-shadow:0 8px 20px rgba(17,24,39,.15)}.nx-btn.ghost{background:#f3f4f6;color:#111827}.nx-btn.good{background:#116530}.nx-btn.warn{background:#9a6700}
  .nx-progress{height:10px;background:#eef1f6;border-radius:99px;overflow:hidden}.nx-progress i{display:block;height:100%;background:linear-gradient(90deg,#7c3aed,#06b6d4);border-radius:99px}
  .nx-chips{display:flex;gap:7px;flex-wrap:wrap}.nx-chip{padding:7px 10px;border-radius:999px;background:#f5f7fb;font-size:.78rem;font-weight:700}
  .nx-flip{perspective:1200px;height:210px;cursor:pointer}.nx-flip-in{height:100%;transition:.55s;transform-style:preserve-3d;position:relative}.nx-flip.open .nx-flip-in{transform:rotateY(180deg)}.nx-face{position:absolute;inset:0;backface-visibility:hidden;border-radius:18px;padding:18px;display:flex;flex-direction:column;justify-content:center}.nx-front{background:linear-gradient(135deg,#f8fafc,#eef2ff)}.nx-back{background:#111827;color:white;transform:rotateY(180deg)}
  .nx-organizer{display:grid;grid-template-columns:1fr 1fr;gap:12px}.nx-node{min-height:78px;padding:14px;border-radius:16px;background:#f8fafc;border:1px dashed #cfd5e1}.nx-node strong{display:block;margin-bottom:5px}
  .nx-video{border-radius:18px;overflow:hidden;background:#0f172a;color:#fff;min-height:180px;display:flex;align-items:center;justify-content:center;text-align:center;padding:22px}.nx-video a{color:#fff;font-weight:800;text-decoration:none;border:1px solid rgba(255,255,255,.28);padding:11px 15px;border-radius:12px;display:inline-block;margin-top:12px}
  .game-shell{display:grid;grid-template-columns:1.45fr .8fr;gap:18px}.game-board{min-height:560px}.game-side{display:grid;gap:16px;align-content:start}.game-head{display:flex;justify-content:space-between;align-items:center;gap:12px}.game-token{font-size:2.2rem;transition:transform .35s}.game-path{display:grid;grid-template-columns:repeat(6,1fr);gap:8px;margin:18px 0}.game-cell{aspect-ratio:1;border-radius:15px;background:#f3f4f6;padding:8px;position:relative;font-size:.72rem;font-weight:800}.game-cell.special{background:#ede9fe}.game-cell.goal{background:#dcfce7}.game-cell .dot{position:absolute;right:7px;bottom:5px;font-size:1.1rem}.game-question{padding:18px;background:#f8fafc;border-radius:18px;margin-top:15px}.game-options{display:grid;gap:9px;margin-top:12px}.game-options button{padding:13px;border-radius:13px;border:1px solid #d8dee9;background:#fff;text-align:left;cursor:pointer;font-weight:700}.game-options button:hover{background:#eef2ff}.game-options button.ok{border-color:#22c55e;background:#dcfce7}.game-options button.no{border-color:#ef4444;background:#fee2e2}
  .jenga{display:grid;grid-template-columns:1fr 1fr;gap:18px}.jenga-tower{min-height:390px;display:flex;flex-direction:column-reverse;justify-content:flex-start;align-items:center;padding:18px}.j-block{height:38px;width:180px;margin:3px 0;border-radius:9px;display:flex;align-items:center;justify-content:center;font-weight:800;cursor:pointer;transition:.2s transform}.j-block:hover{transform:translateX(8px)}.j-block[data-orient="r"]{transform:rotate(2deg)}.j-block[data-orient="l"]{transform:rotate(-2deg)}
  .lab{display:grid;grid-template-columns:1fr 1fr;gap:18px}.lab-controls label{display:grid;gap:6px;margin:12px 0;font-weight:800}.lab-controls input{width:100%}.lab-result{padding:18px;border-radius:18px;background:#f8fafc}.lab-plant{font-size:5rem;text-align:center;padding:20px;transition:.3s transform}.lab-bars{display:grid;gap:8px}.lab-bar{display:flex;align-items:center;gap:8px}.lab-bar span{width:110px;font-size:.82rem}.lab-bar i{height:20px;border-radius:10px;background:linear-gradient(90deg,#22c55e,#84cc16)}
  .route{position:relative;padding:20px;border-radius:22px;background:linear-gradient(145deg,#eff6ff,#f8fafc);min-height:360px}.route-line{display:flex;gap:10px;flex-wrap:wrap;align-items:center;justify-content:center;padding-top:28px}.route-node{width:86px;height:86px;border-radius:50%;background:#fff;border:2px solid #cbd5e1;display:flex;align-items:center;justify-content:center;text-align:center;font-weight:900}.route-node.on{background:#111827;color:#fff;border-color:#111827}.route-arrow{font-size:1.4rem}.route-options{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:18px}
  .memory{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.m-card{aspect-ratio:1;border:0;border-radius:16px;background:#111827;color:#fff;font-size:1.5rem;cursor:pointer;position:relative;overflow:hidden}.m-card span{opacity:0;transition:.2s}.m-card.revealed{background:#eef2ff;color:#111827}.m-card.revealed span,.m-card.matched span{opacity:1}.m-card.matched{outline:3px solid #22c55e;background:#dcfce7}
  .nx-toast{position:fixed;right:18px;bottom:18px;z-index:10000;max-width:320px;padding:13px 16px;border-radius:14px;background:#111827;color:white;font-weight:800;box-shadow:0 18px 40px rgba(0,0,0,.2)}
  .nx-confetti{position:fixed;inset:0;pointer-events:none;z-index:9999}.nx-confetti i{position:absolute;width:9px;height:14px;animation:fall 1.1s ease-out forwards}@keyframes fall{0%{transform:translateY(-10vh) rotate(0);opacity:1}100%{transform:translateY(100vh) rotate(540deg);opacity:0}}
  @media(max-width:920px){.game-shell,.lab,.jenga{grid-template-columns:1fr}.game-path{grid-template-columns:repeat(4,1fr)}.memory{grid-template-columns:repeat(3,1fr)}}
  `;
  const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);

  function toast(text){const t=document.createElement('div');t.className='nx-toast';t.textContent=text;document.body.appendChild(t);setTimeout(()=>t.remove(),2800)}
  function confetti(){const wrap=document.createElement('div');wrap.className='nx-confetti';for(let i=0;i<42;i++){const p=document.createElement('i');p.style.left=(Math.random()*100)+'%';p.style.top=(-Math.random()*10)+'%';p.style.animationDelay=(Math.random()*.35)+'s';p.style.transform=`rotate(${Math.random()*180}deg)`;wrap.appendChild(p)}document.body.appendChild(wrap);setTimeout(()=>wrap.remove(),1600)}
  function award(amount,label){const s=state();s.xp+=amount;s.puntos+=Math.round(amount*.6);s.stats.actividades++;save(s);toast(`+${amount} XP · ${label}`);confetti()}
  function pctCourse(id,delta){const s=state();s.progreso[id]=Math.min(100,Math.max(0,(s.progreso[id]||0)+delta));s.stats.porCurso[id]=(s.stats.porCurso[id]||0)+1;save(s)}
  const videoSearch={matematica:'https://www.youtube.com/results?search_query=fracciones+secundaria+espa%C3%B1ol',comunicacion:'https://www.youtube.com/results?search_query=idea+principal+inferencias+secundaria+espa%C3%B1ol',ciencia:'https://www.youtube.com/results?search_query=m%C3%A9todo+cient%C3%ADfico+secundaria+espa%C3%B1ol',sociales:'https://www.youtube.com/results?search_query=historia+del+Tahuantinsuyo+secundaria+espa%C3%B1ol'};

  function learningToolkit(t,cid){
    const cards=(t.conceptos||[]).slice(0,4).map((term,i)=>`<div class="nx-flip" data-flip><div class="nx-flip-in"><div class="nx-face nx-front"><span class="nx-kicker">Toca para descubrir</span><h3>${esc(term)}</h3><p class="nx-muted">Concepto clave ${i+1}</p></div><div class="nx-face nx-back"><strong>${esc(term)}</strong><p>${esc((t.explicacion||t.intro||'').split('.').slice(0,2).join('. ') + '.')}</p></div></div></div>`).join('');
    return `<section class="nx-zone"><div class="nx-toolbar"><span class="nx-kicker">APRENDE DE OTRA FORMA</span></div><div class="nx-grid"><div class="nx-card"><span class="nx-kicker">🧠 Organizador visual</span><h3 class="nx-title">La idea en 30 segundos</h3><div class="nx-organizer"><div class="nx-node"><strong>1 · ¿Qué es?</strong>${esc(t.intro)}</div><div class="nx-node"><strong>2 · ¿Cómo funciona?</strong>${esc(t.explicacion||'')}</div><div class="nx-node"><strong>3 · Ejemplo</strong>${esc(t.ejemplo||'')}</div><div class="nx-node"><strong>4 · Llévalo a tu mundo</strong>${esc(t.transferencia||'')}</div></div></div><div class="nx-card"><span class="nx-kicker">🎬 Video recomendado</span><h3 class="nx-title">Míralo y vuelve a intentarlo</h3><div class="nx-video"><div><div style="font-size:2.8rem">▶</div><p>Refuerza la idea con una explicación audiovisual.</p><a href="${videoSearch[cid]||videoSearch.matematica}" target="_blank" rel="noopener">Buscar video en YouTube ↗</a></div></div></div></div><div class="nx-card" style="margin-top:16px"><span class="nx-kicker">🃏 Tarjetas activas</span><h3 class="nx-title">Tócalas para comprobar si reconoces los conceptos</h3><div class="nx-grid">${cards}</div></div></section>`;
  }

  function enhanceLearningPage(){
    $$('.lesson-card').forEach(card=>{if($('.nx-mini',card))return;const title=$('h3',card)?.textContent?.trim();const c=(CURSOS||[]).find(x=>x.temas.some(t=>t.titulo===title));const t=c?.temas.find(x=>x.titulo===title);if(!t)return;const box=document.createElement('div');box.className='nx-mini';box.style.marginTop='12px';box.innerHTML=`<div class="nx-chips">${(t.conceptos||[]).slice(0,3).map(x=>`<span class="nx-chip">✦ ${esc(x)}</span>`).join('')}</div><button class="nx-btn ghost" style="margin-top:10px">Aprender con tarjetas →</button>`;card.appendChild(box);box.querySelector('button').onclick=()=>location.href=`leccion.html?curso=${c.id}&tema=${t.id}`});
    const main=$('#app main.main');
    if(main&&!$('.nx-learning-banner')){const banner=document.createElement('section');banner.className='nx-card nx-learning-banner';banner.style.marginBottom='18px';banner.innerHTML=`<div style="display:flex;justify-content:space-between;gap:16px;align-items:center;flex-wrap:wrap"><div><span class="nx-kicker">NUEVO · APRENDIZAJE ACTIVO</span><h2 class="nx-title">No solo leas: mira, juega, relaciona y comprueba.</h2><p class="nx-muted">Cada tema incluye organizadores visuales, tarjetas activas y una ruta audiovisual.</p></div><a class="nx-btn" href="../pages/juegos.html">Ir a juegos →</a></div>`;main.insertBefore(banner,main.children[1]||null)}
  }

  function enhanceLessonPage(){
    const q=new URLSearchParams(location.search),cid=q.get('curso'),tid=q.get('tema');const c=(CURSOS||[]).find(x=>x.id===cid),t=c?.temas.find(x=>x.id===tid);if(!t)return;const main=$('#app main.main');if(!main||$('.nx-zone',main))return;
    const wrap=document.createElement('div');wrap.innerHTML=learningToolkit(t,cid);main.appendChild(wrap.firstElementChild);$$('.nx-flip',main).forEach(el=>el.addEventListener('click',()=>el.classList.toggle('open')));
    const practice=document.createElement('section');practice.className='nx-card nx-zone';practice.innerHTML=`<span class="nx-kicker">⚡ MICRODESAFÍO</span><h2 class="nx-title">Explícaselo a alguien en 20 segundos</h2><p>Sin mirar arriba, selecciona la opción que mejor completa la idea del tema.</p><div class="game-options" id="microopts">${(t.opciones||[]).map((o,i)=>`<button data-i="${i}">${esc(o)}</button>`).join('')}</div>`;main.appendChild(practice);
    $$('#microopts button').forEach(btn=>btn.onclick=()=>{const i=Number(btn.dataset.i),ok=i===t.correcta;$$('#microopts button').forEach(b=>b.disabled=true);btn.classList.add(ok?'ok':'no');toast(ok?'¡Lo conectaste! +25 XP':'Casi. Revisa la explicación y vuelve a intentar.');if(ok){award(25,'Microdesafío');pctCourse(cid,2)}});
  }

  function sidebar(){return `<aside class="sidebar"><a class="brand" href="${base}/index.html"><span class="brand-mark">N</span><span>NEXT <b>LEVEL</b></span></a><div class="nav-label">PLATAFORMA</div><nav><a class="nav-item" href="${base}/index.html"><span>⌂</span>Inicio</a><a class="nav-item" href="${base}/pages/aprender.html"><span>◈</span>Aprender</a><a class="nav-item active" href="${base}/pages/juegos.html"><span>◆</span>Juegos</a><a class="nav-item" href="${base}/pages/retos.html"><span>⚡</span>Retos</a><a class="nav-item" href="${base}/pages/progreso.html"><span>◒</span>Progreso</a><a class="nav-item" href="${base}/pages/perfil.html"><span>●</span>Perfil</a></nav></aside>`}
  function gameHub(){return `<div class="shell">${sidebar()}<main class="main"><div class="topbar"><div><div class="eyebrow">NEXT LEVEL</div><h1>Juega para aprender</h1><p>No son minijuegos al azar: cada uno entrena una habilidad concreta y deja registro de tu avance.</p></div></div><section class="nx-card" style="margin-bottom:18px"><div class="nx-kicker">TU ARSENAL</div><div class="nx-grid" style="margin-top:12px"><div><b>🎲 Ludo Matemático</b><p class="nx-muted">Cálculo mental, operaciones y decisiones bajo presión.</p><button class="nx-btn" data-game="ludo">Jugar →</button></div><div><b>🧱 Jenga de Comunicación</b><p class="nx-muted">Inferencias, conectores y argumentos con riesgo creciente.</p><button class="nx-btn" data-game="jenga">Jugar →</button></div><div><b>🌱 Laboratorio Express</b><p class="nx-muted">Controla variables, predice y descubre qué cambió.</p><button class="nx-btn" data-game="lab">Jugar →</button></div><div><b>🗺️ Ruta del Tahuantinsuyo</b><p class="nx-muted">Avanza por el mapa resolviendo decisiones históricas.</p><button class="nx-btn" data-game="ruta">Jugar →</button></div><div><b>🧠 Memoria NEXT</b><p class="nx-muted">Relaciona conceptos con ejemplos y entrena memoria.</p><button class="nx-btn" data-game="memory">Jugar →</button></div></div></section><div id="gameMount"></div></main></div>`}
  function mountGame(type){const mount=$('#gameMount');if(!mount)return;if(type==='ludo')ludo(mount);if(type==='jenga')jenga(mount);if(type==='lab')lab(mount);if(type==='ruta')ruta(mount);if(type==='memory')memory(mount);mount.scrollIntoView({behavior:'smooth',block:'start'})}

  function ludo(mount){
    const questions=[['En el mercado compras 3 jugos a S/ 4. ¿Cuánto pagas?',['S/ 7','S/ 12','S/ 14','S/ 16'],1],['Si tienes S/ 50 y gastas S/ 18, ¿cuánto queda?',['S/ 28','S/ 32','S/ 36','S/ 38'],1],['¿Cuánto es 3/8 + 2/8?',['5/16','5/8','6/8','1/8'],1],['Un pasaje cuesta S/ 2.50. ¿Cuánto cuestan 4?',['S/ 8','S/ 10','S/ 12.50','S/ 7.50'],1],['Rectángulo de 9 m por 4 m: área?',['13 m²','26 m²','36 m²','45 m²'],2],['5 entradas cuestan S/ 20. ¿Cuánto 8 al mismo precio?',['S/ 24','S/ 28','S/ 30','S/ 32'],3]];
    let pos=0,score=0,qidx=0,waiting=false;const cells=Array.from({length:24},(_,i)=>`<div class="game-cell ${i%5===0?'special':''} ${i===23?'goal':''}" data-cell="${i}">${i+1}${i%4===0?'<span class="dot">✦</span>':''}</div>`).join('');
    mount.innerHTML=`<section class="game-shell"><div class="nx-card game-board"><div class="game-head"><div><span class="nx-kicker">🎲 LUDO MATEMÁTICO</span><h2 class="nx-title">Llega a la meta antes de quedarte sin intentos</h2></div><div class="game-token">🧑‍🚀</div></div><div class="game-path" id="ludoPath">${cells}</div><div id="ludoQ" class="game-question"><b>Tira el dado para comenzar.</b><p class="nx-muted">Cada tirada mueve tu ficha; en casillas especiales aparece un desafío.</p></div></div><aside class="game-side"><div class="nx-card"><span class="nx-kicker">MARCADOR</span><h2 class="nx-title"><span id="ludoScore">0</span> XP</h2><p>Casilla <b id="ludoPos">1</b>/24 · Correctas <b id="ludoCorrect">0</b></p><button class="nx-btn" id="ludoRoll">🎲 Tirar dado</button><button class="nx-btn ghost" id="ludoReset" style="margin-top:8px">Reiniciar</button></div><div class="nx-card"><span class="nx-kicker">REGLA</span><p>Responde bien y recibes XP. Una respuesta incorrecta no te quita XP: te enseña dónde reforzar.</p></div></aside></section>`;
    const render=()=>{$$('.game-cell','#ludoPath').forEach(c=>c.style.outline='');const cell=$(`.game-cell[data-cell="${Math.min(pos,23)}"]`,'#ludoPath');if(cell)cell.style.outline='3px solid #111827';$('#ludoPos').textContent=pos+1};
    const reset=()=>{pos=0;score=0;qidx=0;waiting=false;$('#ludoScore').textContent=0;$('#ludoCorrect').textContent=0;$('#ludoQ').innerHTML='<b>Tira el dado para comenzar.</b><p class="nx-muted">Cada tirada mueve tu ficha; en casillas especiales aparece un desafío.</p>';render()};
    $('#ludoReset').onclick=reset;$('#ludoRoll').onclick=()=>{if(waiting||pos>=23)return;const d=1+Math.floor(Math.random()*6);pos=Math.min(23,pos+d);render();toast(`🎲 Sacaste ${d}`);if(pos>=23){award(80,'Meta del Ludo');$('#ludoQ').innerHTML='<b>🏁 ¡Llegaste a la meta!</b><p>Terminaste el recorrido matemático.</p>';return}if(pos%3===0||pos%5===0){const q=questions[qidx++%questions.length];waiting=true;$('#ludoQ').innerHTML=`<b>${esc(q[0])}</b><div class="game-options">${q[1].map((o,i)=>`<button data-i="${i}">${esc(o)}</button>`).join('')}</div>`;$$('.game-options button','#ludoQ').forEach(b=>b.onclick=()=>{const ok=Number(b.dataset.i)===q[2];$$('.game-options button','#ludoQ').forEach(x=>x.disabled=true);b.classList.add(ok?'ok':'no');if(ok){score+=25;$('#ludoScore').textContent=score;$('#ludoCorrect').textContent=Number($('#ludoCorrect').textContent)+1;award(25,'Respuesta Ludo')}else toast('No pasa nada: revisa el procedimiento y continúa.');waiting=false})}};render();
  }

  function jenga(mount){
    const prompts=[['Conector','“Estudié temprano; ___, terminé tranquilo.”',['por eso','sin embargo','porque'],0],['Inferencia','Ana salió con paraguas y volvió mojada. ¿Qué puedes inferir?',['Probablemente llovió','Es verano','Está en una biblioteca'],0],['Argumento','¿Qué fortalece más una opinión?',['Una razón con evidencia','Mayúsculas','Muchas palabras'],0],['Idea principal','¿Qué resume mejor un texto?',['Su detalle favorito','Su idea central','Una palabra repetida'],1],['Conector','¿Cuál expresa contraste?',['Además','Por eso','Sin embargo'],2]];
    let height=0,removed=0,turn=0;const build=()=>Array.from({length:12},(_,i)=>`<button class="j-block" data-b="${i}" data-orient="${i%2?'l':'r'}">BLOQUE ${i+1}</button>`).join('');
    mount.innerHTML=`<section class="jenga"><div class="nx-card"><div class="game-head"><div><span class="nx-kicker">🧱 JENGA DE COMUNICACIÓN</span><h2 class="nx-title">Quita un bloque. Mantén viva tu torre.</h2></div><div style="font-size:2rem">🧱</div></div><div class="jenga-tower" id="tower">${build()}</div><div id="jengaPrompt" class="game-question"><b>Elige un bloque para empezar.</b></div></div><aside class="game-side"><div class="nx-card"><span class="nx-kicker">ESTABILIDAD</span><h2 class="nx-title"><span id="stable">100</span>%</h2><div class="nx-progress"><i id="stableBar" style="width:100%"></i></div><p>Bloques retirados: <b id="removed">0</b>/12</p><button class="nx-btn ghost" id="jReset">Rearmar torre</button></div><div class="nx-card"><p class="nx-muted">Cada bloque activa un desafío. Una respuesta correcta estabiliza la torre; un error aumenta el riesgo.</p></div></aside></section>`;
    function reset(){height=0;removed=0;turn=0;$('#tower').innerHTML=build();$('#stable').textContent=100;$('#stableBar').style.width='100%';$('#removed').textContent=0;bind()}
    function fail(){height+=12;const v=Math.max(0,100-height);$('#stable').textContent=v;$('#stableBar').style.width=v+'%'}
    function bind(){$$('.j-block','#tower').forEach(b=>b.onclick=()=>{const q=prompts[turn++%prompts.length];$('#jengaPrompt').innerHTML=`<span class="nx-kicker">${q[0]}</span><p><b>${esc(q[1])}</b></p><div class="game-options">${q[2].map((o,i)=>`<button data-i="${i}">${esc(o)}</button>`).join('')}</div>`;$$('.game-options button','#jengaPrompt').forEach(opt=>opt.onclick=()=>{const ok=Number(opt.dataset.i)===q[3];$$('.game-options button','#jengaPrompt').forEach(x=>x.disabled=true);opt.classList.add(ok?'ok':'no');b.remove();removed++;$('#removed').textContent=removed;if(ok){award(22,'Jenga correcto');height=Math.max(0,height-4)}else{fail();toast('La torre se tambaleó. Refuerza esa habilidad.')}if(removed===12){award(90,'Torre completada');$('#jengaPrompt').innerHTML='<b>🏆 Torre completada.</b><p>Superaste todos los bloques sin derribar el aprendizaje.</p>'}})})}
    $('#jReset').onclick=reset;bind();
  }

  function lab(mount){
    mount.innerHTML=`<section class="lab"><div class="nx-card lab-controls"><span class="nx-kicker">🌱 LABORATORIO EXPRESS</span><h2 class="nx-title">¿Qué hace crecer más a una planta?</h2><p class="nx-muted">Manipula una variable a la vez. Antes de revelar el resultado, haz una predicción.</p><label>Luz <input id="light" type="range" min="20" max="100" value="70"><span id="lightV">70</span>%</label><label>Agua <input id="water" type="range" min="20" max="100" value="60"><span id="waterV">60</span>%</label><label>Nutrientes <input id="nutrient" type="range" min="20" max="100" value="50"><span id="nutV">50</span>%</label><button class="nx-btn" id="predict">🔬 Ejecutar experimento</button></div><div class="nx-card lab-result"><div class="lab-plant" id="plant">🌱</div><div class="lab-bars"><div class="lab-bar"><span>Crecimiento</span><i id="grow" style="width:0%"></i></div><div class="lab-bar"><span>Salud</span><i id="health" style="width:0%"></i></div></div><div id="labText" style="margin-top:14px"><b>Tu hipótesis:</b> ajusta los controles y ejecuta.</div></div></section>`;
    [['light','lightV'],['water','waterV'],['nutrient','nutV']].forEach(([a,b])=>{$('#'+a).oninput=()=>$('#'+b).textContent=$('#'+a).value});
    $('#predict').onclick=()=>{const l=+$('#light').value,w=+$('#water').value,n=+$('#nutrient').value;const growth=Math.round(l*.35+w*.35+n*.3);const health=Math.round(100-Math.abs(l-w)*.25-Math.abs(w-n)*.2);$('#grow').style.width=Math.min(100,growth)+'%';$('#health').style.width=Math.max(0,health)+'%';$('#plant').style.transform=`scale(${.8+growth/300})`;$('#labText').innerHTML=`<b>Resultado:</b> crecimiento estimado <strong>${growth}%</strong>.<p>Tu diseño cambia tres variables; para investigar mejor, modifica solo una y compara dos pruebas.</p>`;award(30,'Experimento CYT');pctCourse('ciencia',3)};
  }

  function ruta(mount){
    const qs=[['Llegas a un tambo en un camino del Tahuantinsuyo. ¿Qué ayudaba al intercambio de información?',['Chasquis','Semáforos','Radio FM'],0],['¿Qué sistema registraba cuentas mediante cuerdas y nudos?',['Quipu','Kero','Pututo'],0],['Cusco fue un centro político del Tahuantinsuyo. ¿Qué implica?',['Concentraba funciones de gobierno','Solo era un puerto','Era una ciudad moderna'],0],['¿Qué obra conectaba territorios?',['Qhapaq Ñan','Metro subterráneo','Autopista moderna'],0]];let step=0;
    mount.innerHTML=`<section class="nx-card"><span class="nx-kicker">🗺️ RUTA DEL TAHUANTINSUYO</span><h2 class="nx-title">Avanza desde Cusco resolviendo decisiones</h2><div class="route"><div class="route-line" id="routeLine">${['Cusco','Valle','Sierra','Costa','Meta'].map((x,i)=>`${i?'<span class="route-arrow">→</span>':''}<div class="route-node ${i===0?'on':''}" data-r="${i}">${x}</div>`).join('')}</div></div><div id="routeQ" class="game-question"><b>Comienza la ruta.</b><button class="nx-btn" id="routeStart" style="margin-top:10px">Empezar</button></div></section>`;
    $('#routeStart').onclick=next;
    function next(){if(step>=qs.length){award(70,'Ruta completada');$('#routeQ').innerHTML='<b>🏁 Llegaste a la meta.</b><p>Conectaste geografía, organización y comunicación histórica.</p>';return}const q=qs[step];$('#routeQ').innerHTML=`<b>${esc(q[0])}</b><div class="route-options">${q[1].map((o,i)=>`<button class="nx-btn ghost" data-i="${i}">${esc(o)}</button>`).join('')}</div>`;$$('.route-options button','#routeQ').forEach(b=>b.onclick=()=>{const ok=+b.dataset.i===q[2];$$('.route-options button','#routeQ').forEach(x=>x.disabled=true);b.classList.add(ok?'good':'warn');if(ok){step++;pctCourse('sociales',3);award(20,'Decisión histórica');$(`[data-r="${step}"]`,'#routeLine')?.classList.add('on');setTimeout(next,500)}else toast('Ese camino no encaja con la evidencia. Revisa el tema y prueba otra vez.')})}
  }

  function memory(mount){
    const pairs=[['Fracción','Parte de un todo'],['Perímetro','Borde de una figura'],['Inferencia','Conclusión a partir de pistas'],['Hipótesis','Explicación que se puede poner a prueba'],['Quipu','Registro con cuerdas y nudos'],['Conector','Une ideas y muestra relación']];
    const deck=pairs.flatMap((p,i)=>[{k:i,t:p[0]},{k:i,t:p[1]}]).sort(()=>Math.random()-.5);let open=[],matches=0,lock=false;
    mount.innerHTML=`<section class="nx-card"><span class="nx-kicker">🧠 MEMORIA NEXT</span><h2 class="nx-title">Encuentra las parejas: concepto ↔ significado</h2><p class="nx-muted">Menos vueltas = mejor dominio.</p><div class="memory" id="memoryGrid">${deck.map((c,i)=>`<button class="m-card" data-k="${c.k}" data-i="${i}">?</button>`).join('')}</div><div style="margin-top:14px">Parejas <b id="matches">0</b>/${pairs.length}</div></section>`;
    $$('.m-card','#memoryGrid').forEach(btn=>btn.onclick=()=>{if(lock||btn.classList.contains('matched')||btn.classList.contains('revealed'))return;btn.classList.add('revealed');btn.innerHTML=`<span>${esc(deck[+btn.dataset.i].t)}</span>`;open.push(btn);if(open.length===2){lock=true;const [a,b]=open;if(a.dataset.k===b.dataset.k){a.classList.add('matched');b.classList.add('matched');matches++;$('#matches').textContent=matches;award(18,'Pareja de memoria');open=[];lock=false;if(matches===pairs.length)award(80,'Memoria completa')}else setTimeout(()=>{a.classList.remove('revealed');b.classList.remove('revealed');a.textContent='?';b.textContent='?';open=[];lock=false},750)}})
  }

  function enhanceGamesPage(){ $('#app').innerHTML=gameHub(); $$('#app [data-game]').forEach(b=>b.onclick=()=>mountGame(b.dataset.game)) }
  if(page==='juegos')enhanceGamesPage();
  if(page==='aprender')enhanceLearningPage();
  if(page==='leccion')enhanceLessonPage();
})();